print("Enter 5 characters to convert to ASCII")
char_1 = input("please enter the 1st character ")
char_2 = input("please enter the 2nd character ")
char_3 = input("please enter the 3rd character ")
char_4 = input("please enter the 4th character ")
char_5 = input("please enter the 5th character ")
print("-----------------------------------")
print("character  |    binary     |    hex")
print("   ", char_1,"       ", bin(ord(char_1)),"      ", hex(ord(char_1))  )
print("   ", char_2,"       ", bin(ord(char_2)),"      ", hex(ord(char_2))  )
print("   ", char_3,"       ", bin(ord(char_3)),"      ", hex(ord(char_3))  )
print("   ", char_4,"       ", bin(ord(char_4)),"      ", hex(ord(char_4))  )
print("   ", char_5,"       ", bin(ord(char_5)),"      ", hex(ord(char_5))  )