print()
print("Think of a number between 0 and 100 inclusive\n")
print("The program will print out a number and wait for your input\n")
print("If the number is lower than your secret number enter the character L")
print("If the number is higher than your secret number enter the character H")
print("If the number is equal to your secret number enter the character E")
print("The program gets 7 chances to guess your number")
print("If it guesses your number it will print out the number of guesses it took")
print()

